### ISSUE TITLE
과제에 관한 질문

### ISSUE THREAD

**Issue by ansungjae** [Song-175/WebBasic-23Y1S-063#1]
## 질문 요약
1.
2. 
3. 

## 질문 상세
추측이지만 제가 맥북으로 코드를 써서그런지, 과제로 나온 글꼴과 제가 만든 것의 글꼴이 다른데 이런 상황에서는 어떻게 해야 하나요?

## 관련 화면
<img width="667" alt="스크린샷 2023-03-29 오후 5 01 39" src="https://user-images.githubusercontent.com/129068225/228467740-74e4fc65-eae0-4f18-91e0-c1afe94c2b70.png">

<img width="907" alt="스크린샷 2023-03-29 오후 5 08 13" src="https://user-images.githubusercontent.com/129068225/228468908-cca027ad-faec-41a9-bda0-566816aae2ef.png">

**Comment by Song-175** [comment]
과제 채점은 windows 환경에서 이루어지기 때문에, 동일 코드지만 구동 환경에 의해 일부 글꼴이 다르게 표현되는 문제라면 점수에 영향은 없으므로 그대로 제출해주시면 됩니다.

감사합니다.
