### ISSUE TITLE
텀 프로젝트 추가 구현 사항 가산점에 대한 기준에 관해 질문드립니다!

### ISSUE THREAD

**Issue by wannabidr** [Song-175/WebBasic-23Y1S-063#2]
## 질문 요약
1. 텀 프로젝트 추가 구현 사항에 대한 기준

## 질문 상세

텀 프로젝트 추가 구현 사항 가산점 기준에 대해서 질문드립니다.
최소 개발 구현 사항과 유사한 내용으로 구현한 코드가 있는 경우 작성하면 되는지,
최소 개발 구현 사항에 없는 내용으로 구현한 코드가 있어야하는건지 궁금합니다.

**Comment by Song-175** [comment]
최소 개발 구현에 없는 내용으로 추가 구현을 진행하셔야 하고, 외부 API나 라이브러리를 사용하는것은 가산점을 드리지 않습니다.
